### PR TITLE
Update to eoan; update package versions

### PR DESCRIPTION
**Pull request by james-callahan**

### CODE REVIEW

**Comment by ypid** [comment]
I would rather directly switch to Debian buster, ref #4. Out of interest, how many builds have you made/tested using eoan?

**Comment by james-callahan** [comment]
> I would rather directly switch to Debian buster, ref #4.

go for it!

> how many builds have you made/tested using eoan?

none; I got stuck further down the instruction list...
But cosmic was broken for me; upgrading to eoan at least got to the next thing...

**Comment by ypid** [comment]
All right. Cosmic should work. I will leave this PR open until an alternative one switching the project to Debian exists.

**Comment by ypid** [comment]
Closed by #31.

**Pull request closed without merging**
