### PR TITLE
Android 11 and Debian 10 base image

### PR DESCRIPTION
**Pull request by ypid**
I decided to push my draft WIP state now because I just found https://github.com/mobilesec/reproducible-builds-aosp which has many similarities with this project and I would like sync up with @mpoel.

Closes: #31

Hi @mpoel

It seems you have started a project on 2019-10-16 that is similar to this one. It might make sense to join forces? I would also be interested if you considered any of the known projects (refs: [1](https://github.com/AOSPAlliance/README), [2](https://github.com/Peter-Easton/GrapheneOS-Knowledge/blob/master/GrapheneOS-vs-Others.md)) in the AOSP-based hardening community? I checked your code right now. You have slightly different goals than this project does, but still pretty similar direction. I am also very interested in reproducible builds. What your project does not do is locking all it’s build inputs. I will probably read over your Bachelor’s thesis the next days. Until then, I just want to ping you as you also worked on your project today, same as me.

This PR is a draft, but it can give you an idea of the current state of the project. Note that I have not tested building AOSP with this PR. I just built GrapheneOS with it for now.

### CODE REVIEW

**Comment by mpoel** [comment]
Hello,

Thanks for pinging me and the the interest in https://github.com/mobilesec/reproducible-builds-aosp . It's a project from the Institute of Networks and Security at the Johannes Kepler University Linz, with me being the main developer currently. There are indeed quite a few similarities between our project and this one. I did stumble upon this repository when researching the requirements for our project, but in the end settled to implement simple shell scripts based on the instruction from https://source.android.com myself. The primary goal of our project is to perform the official build instructions, only deviating when there's no other way (e.g. additional APT dependencies that are not properly documented), and analyzing the output w.r.t. to reference builds. Inspecting the scripts of this repository leads me to believe that there are certain changes that deviate from the reference instructions (e.g. `apply_patches` in `scripts/build`). Undoubtedly there are good valid reasons for your project to do this, but that is one of the reasons why I've settled on creating a new project with our very specific goals in mind. I'm not sure yet about specific collaboration efforts, in part since I would probably need to coordinate this with others folks at the INS department at the university. However, if you have any questions about our project, please don't be shy with asking :)

With regards to the other projects you mentioned (GrapheneOS, LineageOS, and similar): A similar argument to the one from above applies to these. Many of them are focused on augmenting the standard AOSP builds with additional features or security measures, which is interesting in its own right, not quite what we need. If you know of any other project that aims to build AOSP in a completely unchanged way, please let me know (minus robotnix, whose author @danielfullmer we are already in touch with).

However, you are fully correct that the lack of a locking mechanism of the input dependencies (i.e. apt and pip packages) is a weakness of our project as of now and something worth looking into for the future.

**Comment by ypid** [comment]
Thanks for your answer.

> (e.g. apply_patches in scripts/build).

This is configurable from the config file ;-)

So to clarify, this project https://github.com/hashbang/aosp-build is then exactly what you are looking for. A build system for unmodified or with only necessary changes to build it AOSP. The stuff I was talking about is just my use case that is developed in another repo (https://github.com/hashbang/os) which just uses the Docker image and bundled default scripts aosp-build provides.

I don’t know other projects except the once we already mentioned. Except https://ci.android.com which would be interesting to look at. But even if we had access to the scripts, I guess their use case and threat model is different.

Lets do it like this, I can ping you when the Android 11 and Debian 10 work has been merged into master, and I have possibly tested building an unmodified AOSP with it, then you can take a look and discuss this in your department.

**Comment by ypid** [comment]
> Lets do it like this, I can ping you when the Android 11 and Debian 10 work has been merged into master, and I have possibly tested building an unmodified AOSP with it, then you can take a look and discuss this in your department.

@mpoel
I did not do exactly that, but something else. I implemented signature verification of build inputs #32 and redefined the way other projects can make use of aosp-build (https://github.com/hashbang/os/pull/49). I did not test building AOSP but there should only be very minimal changes needed, if any. I could kick of a build if it helps. I looked into your bachelor thesis, nice work! Some day I might come back to that in case I decide to work on the HashbangMobile project goal of multisig requirement for the updater. Until then, let me know if I can help. You could consider aosp-build now for your own use.

**Comment by mpoel** [comment]
Thanks for keeping me updated. I tested your work on this PR (as of commit [a550c23](https://github.com/hashbang/aosp-build/pull/31/commits/a550c23133629da2d6948971cd1bab34eaac23b9)) in a clean installation of an Ubuntu 20.04 VM, attempting build a standard AOSP build for the crosshatch device. As instructed in the `README` I simply executed `make DEVICE=crosshatch` to perform a build with the local backend. Here are my findings:
1. Initially the build process failed due to the missing Python Jinja library (on the host system, not in the docker container). Obviously trivial to fix via `apt-get install python-jinja2`, I'd recommend documenting this requirement
2. I opted to add my user to the docker group and thus execute docker commands without sudo. With a clean clone of the aosp-build repo this results in the creation of some directories with root ownership (needed for the volumes, I assume the docker deamon creates these). Since the `docker run` command uses id 1000, this subsequently gave me permission denied errors inside docker. My temporary workaround is to create these folder ahead of the Makefile invocation with my local user myself. Specifically these folders are `build`, `release` and `keys`. Not sure how to propely handle this.
3. Some of the pinned version in the `packages-pinned.list` are already outdated. My most recent docker build command was executed roughly 48 hours ago and I had to update several package versions (see attached patch for details). I fully agree that pinned dependencies are necessary for reproducible builds, that's just an unfortunate side effects of the fast moving package ecosystem.
4. Building the kernel initially aborted with the error `/home/build/build/external/kernel/crosshatch/private/msm-google/scripts/sign-file.c:25:10: fatal error: 'openssl/opensslv.h' file not found`. Fixed by adding `libssl-dev` to the `package.list`
5. Finally there seems to be some inconsistency with the targeted android version and build ids scattered across the files. Notabley for crosshatch I've encountered: a) In the `config/config.yml` the `platform_ref` has the value `android-11.0.0_r29`, but b) the `config/manifests/crosshatch/base.xml` file points to the `android-10.0.0_r22` release (including your fork for android-prepare-vendor, which does not support API-30 for Android 11 yet). This resulted in an error as well, for now I've opted to adjust the values in the `config/config.yml` to the older `àndroid-10.0.0_r22` release.

Attached you find a full patch that encompasses the points mentioned above and enabled me run a full build. I hope this helps and is interesting to you. Obviously, feel free to ask for more details. I like your project and it's great to offer multiple backends (SOAP effectively has 3 as well, native, docker and Jenkins), but I don't want to promise you too much. We've already got our infrastructure set up and running well with our Jenkins integration for some basic monitoring. You probably know the saying with the running systems and such. But it would definitely be interesting to perform builds with aosp-build in addition to our SOAP builds and generate SOAP difference reports for them.

Patch: 
[patch.zip](https://github.com/hashbang/aosp-build/files/5978228/patch.zip)

**Comment by ypid** [comment]
That is very valuable feedback. Thank you! It also means that I did not break Android 10 support which is good to know :)

> the config/manifests/crosshatch/base.xml file points to the android-10.0.0_r22

I did not bother to update manifests for devices other than sargo to be honest. Did that now.

> Some of the pinned version in the packages-pinned.list are already outdated.

I have been thinking about this as well. I will need to switch to https://snapshot.debian.org/.

> You probably know the saying with the running systems and such.

Got it :)

I will go over your other points in a few weeks.

**Comment by ypid** [comment]
> I have been thinking about this as well. I will need to switch to https://snapshot.debian.org/.

Done that.

**Comment by ypid** [comment]
I should probably merge that. Otherwise people would need to submit patches/base their work on my branch/this PR.

**Pull request merged**
