### PR TITLE
Namespace manifests and remove Chromium

### PR DESCRIPTION
**Pull request by lrvick**
# WIP - Do Not Merge

## Removing chromium

1. Chromium is not a part of AOSP and the scope of aosp-build is to deterministically compile AOSP. 
2. Browsers need to be updated frequently and should likely not ship with an OS which is updated infrequently.
3. Not all users want Chromium at all or may wish to have specific forks of it to their preferences.
4. It adds an extra 24h+ to the build time for most users making the project inaccessible
5. Those wishing to see proper chromium support should support adding Bromite to the F-Droid build system (which paves the way for vanilla and other forks as well)

## Namespacing manifests

Almost every device ends up being pinned to different versions upstream as most revisions only fix things on a specific device. Forcing a rebuild on all devices is very time consuming and wasteful.

Opt instead to have a dedicated folder to hold the respective manifest files for every device all version/hash pinned as appropriate for that device.

Also opt to have "make manifest" generate/lock manifests for all devices at once.

### CODE REVIEW

**Review by ypid — COMMENTED** [review]
Looks good to me. I already commented on the Chromium part here https://github.com/hashbang/os/pull/40#issuecomment-581143267, removing it from aosp-build is a good idea.

I will do some more testing of your changes when I build 2020-02-05 the next days.

This PR addresses: https://github.com/hashbang/aosp-build/issues/11

**Comment by dan-v** [comment]
I think removing Chromium build makes sense for aosp-build (maybe we could have a chromium-build project as well?). For anyone directly using aosp-build without modifications, I think it should be made clear it will include the default AOSP webview which is not up to date and may have security issues and if they intend to run this as a production build, it should include a replacement webview.

**Comment by lrvick** [comment]
@dan-v @ypid 

Just did a successful build. Ready for review.

**Review by ypid — APPROVED** [review]
LGTM. I actually tested https://github.com/hashbang/aosp-build/pull/18/commits/5e1cd1327f02fe90d98e0dde6f9f6c972483fe81 and then did the few compatibility changes myself. They are now included in https://github.com/hashbang/aosp-build/pull/18/commits/e5c57e179ad45313ada31edfd4f470e47703640f which I also reviewed and rebased onto. Looks good. Confirmed working on sargo.

**Pull request merged**
