### PR TITLE
Hotfix to build 2020-06-05

### PR DESCRIPTION
**Pull request by ypid**
~~Maybe more changes are needed.~~ Seems to be all that is required to build it.

### CODE REVIEW

**Comment by ypid** [comment]
@lrvick Can you maybe give me push access for now? I would still use PR but with push access, I could maintain a working master branch. You can revert this at any time when you have more time for the project of course.

**Comment by lrvick** [comment]
Yeah I just moved and changed jobs so my life is complicated atm. I have a new pixel 4 to run aosp-build on but have not gotten to it yet. Once I do I'll need to be in the review/build cycle to keep this maintained again.

What is in master is not useful at the moment, so I take your point. I would for sure want there to be strict code review before we do public releases, but those are not happening in the short term until I get some more cycles anyway.

Maybe we could make a "dev" branch you can push directly to as you like as an integration branch and we can merge from dev to master when a second admin has reviewed/built/tested?

Option B is we just consider master to be dev and cut carefully reviewed releases in the future when we are ready to do that.

I'll hopefully be able to get back to this in a couple weekends once I get settled down a bit either way.

**Comment by lrvick** [comment]
Yeah, on considering, I am good to let you co-maintain master for hashbang/aosp-build and hashbang/os for the time being as long as you continue to sign your commits so I can attribute them to you to easily review them before we make releases in the future.

I just don't have enough cycles atm and @dgrove is awal as well.

This project has no public releases and it is on each individual that wants to use it to review for themselves for now, which I will also do.

Your contributions so far have been solid so you have earned a lot of trust with me.

**Comment by lrvick** [comment]
Done! I reserve the right to revisit this when it is determined you are a government spy planting backdoors :)

**Comment by ypid** [comment]
> Done! I reserve the right to revisit this when it is determined you are a government spy planting backdoors :)

Works for me :)

> as long as you continue to sign your commits

Sure, also merge-commits. I am used to this way.

Always a pleasure to work with security-minded people :)

**Comment by ypid** [comment]
Thanks for the trust. I also think that the master branch only is enough for now. No need to over complicate it right now. People who use this or even base on it will hash lock this work in some way after careful review.

Hope you get some time. I can also not dedicate too much time other than keeping up with the monthly patches currently. I guess I will get more into this again when Android 11 gets released.

**Pull request merged**
